<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use GuzzleHttp\Client as Client;
use App\Models\MbMaster;

class TestDingtalk extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:test-dingtalk';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        //
        $dingtalkEndpoint = env('DINGTALK_ROBO');
        $client = new Client();
        $jsonArray = [
            'msgtype' => 'text',
            'text' => [
                'title' => 'New Robustness  Test Recap',
                'content'  => $this->messageCreation(),
                'hideAvatar' => '0',
                'btnOrientation' => '0',
                'btns' => [
                    [
                        'title'     => 'Details',
                        'actionUrl' => 'https://goo.gl/8FZyhp',
                    ],
                ],
            ],
            'at' => [
                'atMobiles' => [
                    // '+6287897066241', // aditya
                    // '+6281382476657', // dimas
                    // '+6281977180180', // dodo
                    // '+62818969365'    // victor
                ],
                'isAtAll' => false
            ],
        ];
        $request = new \GuzzleHttp\Psr7\Request(
            'POST',
            $dingtalkEndpoint,
            [
                'Content-Type' => 'application/json'
            ],
            json_encode($jsonArray)
        );
        $response = $client->send($request);
    }

    private function messageCreation($mbMaster, $action)
    {
        $timeNow = \Carbon\Carbon::now()->format('d-m-Y H:i:s');

        // Tentukan tema warna/emoji berdasarkan action
        $isDeactivated = ($action === 'DEACTIVATED');
        $headerEmoji   = $isDeactivated ? '🚫' : '✅';
        $statusLabel   = $isDeactivated ? '*OFF (Disabled)*' : '*ON (Enabled)*';

        $recapMessage = "{$headerEmoji} *MB STATUS CHANGE REPORT*\n";
        $recapMessage .= "------------------------------------------\n";
        $recapMessage .= "📢 Action: *{$action}*\n";
        $recapMessage .= "📅 Date  : `{$timeNow}`\n\n";

        $recapMessage .= "Detail Brand:\n";
        $recapMessage .= "• Barcode: `{$mbMaster->manufacture_barcode}`\n";
        $recapMessage .= "• Brand  : *{$mbMaster->brand_name}*\n";
        $recapMessage .= "• Status : {$statusLabel}\n\n";

        $recapMessage .= "⚠️ _Catatan: Barcode ini merupakan bagian dari Multi-Brand._\n";
        $recapMessage .= "------------------------------------------\n";
        $recapMessage .= "🤖 _Auto-generated by System_";

        return $recapMessage;
    }

    private function checkMB() {
        $mbMaster = MbMaster::where('is_disabled','1')->get();
        return $mbMaster;
    }
}
